from . import sale_order
from . import sale_order_line
from . import sale_order_catalog_wizard
from . import product_dashboard
from . import product_product_other_item
from . import product_schedule_wizard
from . import product_category
from . import maintenance_equipment
from . import rental_report
from . import maintenance_request
from . import sales_catalog_asset_allocation
from . import sales_catalog_parking_allocation
from . import stock_lot
from . import asset_allocation_add_qty_wizard
from . import parking_allocation_add_qty_wizard
